---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: fedora:29
  commands:
  - "echo \"Hello, world!\""
  - "echo \"Hello, Tom!\""
  - "echo \"Hello, A!\""

...
